### ISSUE TITLE
What is expected to happend?

### ISSUE THREAD

**Issue by francescosisini** [AdamInTheOculus/dog-gone-wild#1]
Goodmorning, I succesfully install the game on Linux. After lounched start.sh a man walk but what else? Thak you

**Comment by AdamInTheOculus** [comment]
Hey @francescosisini thank you for looking at my game! Unfortunately it is **far from finished**. As you can see, I only have animations complete.

There is no gameplay implemented, yet. But I will continue working on it!

Have a nice day.
